version: "3.3"
services:
  resonite:
    image: kal47/resonite-headless:latest
    container_name: resonite-headless
    tty: true
    stdin_open: true
    environment:
      STEAMBETA: headless
      STEAMBETAPASSWORD: CHANGEME
      STEAMLOGIN: "USER PASSWORD"
    volumes:
      - resonite-data:/home/steam/resonite-headless
      - ./Config:/Config:ro
      - ./Logs:/Logs
      - ./Libraries:/Libraries
      - ./rml_libs:/rml_libs
      - ./rml_mods:/rml_mods
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
volumes:
  resonite-data:
